### ISSUE TITLE
Проблема с виртуализацией 64-битной Ubuntu под VMWare

### ISSUE THREAD

**Issue by sewa312** [AlexeyMz/docker-squash#2]
Docker для работы требует 64-битную систему, однако возникли трудности с запуском Ububtu x64 под VMWare. При попытке запуска установленной системы возникает ошибка VMWare, предотвращающая старт ОС.

**Comment by AlexeyMz** [comment]
Возможно в BIOS / UEFI отключена поддержка виртуализации VT-x

**Comment by sewa312** [comment]
Действительно, после включения VT-x проблема разрешилась.
