### ISSUE TITLE
Изучить спецификацию image-файлов Docker

### ISSUE THREAD

**Issue by AlexeyMz** [AlexeyMz/docker-squash#3]
Проанализировать [спецификацию](https://github.com/docker/docker/blob/master/image/spec/v1.md), выделить сведения о структуре image-файла. Ключевые моменты, на которые следует обратить внимание:
- бинарная структура image-файла,
- связь Image-файлов между собой в цепочку,
- способ хранения и содержание метаинформации об image-файлах.

**Comment by sewa312** [comment]
Рекомендую следующую статью к ознакомлению: [Образы и контейнеры Docker в картинках](http://habrahabr.ru/post/272145/)

**Comment by sewa312** [comment]
В догонку habrahabr.ru/post/247903/
