### ISSUE TITLE
Проблема с запуском демона Docker

### ISSUE THREAD

**Issue by sewa312** [AlexeyMz/docker-squash#4]
При попытке запуска демона Docker возникает ошибка, приведённая на скриншоте.
![docker_deamon_issue](https://cloud.githubusercontent.com/assets/16035799/11710750/7e38b922-9f32-11e5-9063-1f0dbe36174a.jpg)

**Comment by AlexeyMz** [comment]
Попробуй запустить docker от суперпользователя (через sudo).

**Comment by sewa312** [comment]
При запуске от суперпользователя возникла другая проблема, с неясным содержанием: 
![docker_deamon_issue_2](https://cloud.githubusercontent.com/assets/16035799/11710798/dcfeee18-9f32-11e5-9cc4-1762f919477c.jpg)

**Comment by AlexeyMz** [comment]
Хм, странная, по-видимому, ubuntu установлена.
Судя по всему, на некоторых дистрибутивах по-умолчанию отключены cgroups, которые требются для функционирования docker.
Можно попробовать [следующее решение](http://awhitehatter.me/debian-jessie-wdocker/):
1. добавить в `/etc/default/grub` строку следующего вида: 
`GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory swapaccount=1"`
2. выполнить `sudo update-grub` и перезагрузить систему.

**Comment by sewa312** [comment]
Отлично, проблема решена.
